apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 3  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: shop:latest
          ports:
            - containerPort: 80  # Port your application listens on
